### ISSUE TITLE
add consolidateby support to graph rendering 

### ISSUE THREAD

**Issue by dgryski** [dgryski/carbonapi#124]
Trying to graph max latencies with cairo, it sucks that they get averaged together when trying to plot a single point.  I'd prefer to be able to say "use the max" or something instead.

**Comment by Dieterbe** [comment]
like graphite's consolidateBy() ? Nnote: in graphite this actually doesn't work very well because it may select data aggregated from whisper using a different function, see https://blog.raintank.io/25-graphite-grafana-and-statsd-gotchas/#runtime.consolidation . not sure if that applies to the booking stack . (in metric-tank consolidateBy controls runtime consolidation as well as the rolled up archive being chosen)

**Comment by dgryski** [comment]
Yes, that's exactly what I need. Thanks.

**Comment by dgryski** [comment]
Fixed by https://github.com/dgryski/carbonapi/commit/f28c4fc59ca02c9aa1d618d7550146d1ec4238aa
