### ISSUE TITLE
Directions on how to run this code.

### ISSUE THREAD

**Issue by rabun788** [dgryski/carbonapi#125]
Having trouble understanding how to run this code, i keep getting undefined errors.

``vagrant@ops-ubuntu-14:$ go run main.go``
 command-line-arguments
./main.go:54: undefined: bytesCache
./main.go:143: undefined: truthyBool
./main.go:152: undefined: truthyBool
./main.go:192: undefined: dateParamToEpoch
./main.go:193: undefined: dateParamToEpoch
./main.go:199: undefined: metricData
./main.go:201: undefined: metricRequest
./main.go:201: undefined: metricData
./main.go:205: undefined: parseExpr
./main.go:205: too many errors`

**Comment by dgryski** [comment]
Please use `go build` to generate the binary. Note you must also have a carbonzipper / carbonserver setup.

**Comment by rabun788** [comment]
I'm running this but still get an error.

`go get -u github.com/dgryski/carbonapi`

./png.go:216: undefined: draw.Point
./png.go:217: undefined: draw.Point
...

**Comment by shurcooL** [comment]
Looks like a valid issue because https://github.com/gonum/plot/blob/master/vg/draw/canvas.go does not have a `type Point` that https://github.com/dgryski/carbonapi/blob/8af3697dac909a184b1376508b79bda0c3085c64/png.go#L216 refers to.

It looks related to https://github.com/gonum/plot/pull/261/files#diff-1318fd408b6d3ed0d6f955e9771b68e3L673.

**Comment by dgryski** [comment]
Grr.  We run with the cairo backend in production :/

I'm seriously tempted to remove the `plot` backend, since it was an experiment that never got enough love.  Once we had the cgo bindings to cairo, that's where all the development went.

**Comment by rabun788** [comment]
@dgryski Are you aware of any other alternatives that we could use, or would you be able to try to fix this in a month or two? Not trying to be pushy, just trying to understand a timeline if there is one.  :)

**Comment by dgryski** [comment]
Do you specifically need the graph rendering code?  If not, it's easy to write a null PNG rederer backend that just reports a "not supported" error, and then you can build with that instead of the broken PNG backend.

If you need graph rendering, I suggest you use the cairo backend.

As I said, I'm tempted to remove the pure-Go PNG rendering code..

**Comment by rabun788** [comment]
we do not need the graph rendering code. do you happen to have the null PNG renderer written?
