### ISSUE TITLE
JSON should support stacked metrics 

### ISSUE THREAD

**Issue by dgryski** [dgryski/carbonapi#150]
Needed for grafana

**Comment by Dieterbe** [comment]
what does this mean? how do you "stack" numbers in json?

**Comment by dgryski** [comment]
Currently the stacked graph code is tied to the Cairo renderer.  We have some stacked graphs at work that fail with grafana's flot renderer but look fine with png. If this is a user error or grafana restriction we can close this.

**Comment by Dieterbe** [comment]
stacking in grafana is just a viz option in the renderer that should have no effect on the http request or response to/from graphite.  I used the devtools network inspector to confirm this. requests and responses look identical whether stacked is enabled in grafana or not.

I still don't understand what you expect a "stacked" json response to look like, how it should differ from a normal response, or what you believe the problem is in your responses.

**Comment by dgryski** [comment]
Hmm.. I'll poke @Civil to investigate this more on Monday.

**Comment by dgryski** [comment]
Closing.
